version: "3.9"

services:
  postgres_source:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 321
      POSTGRES_DB: source_db
    ports:
      - "5432:5432"
    volumes:
      - pg_source_data:/var/lib/postgresql/data

  postgres_target:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: target_db
    ports:
      - "5433:5432"
    volumes:
      - pg_target_data:/var/lib/postgresql/data

volumes:
  pg_source_data:
  pg_target_data: